### ISSUE TITLE
BaseTransform 报错 Failed to copy full contents from 

### ISSUE THREAD

**Issue by protectedMan** [leavesC/ASM_Transform#6]
Caused by: java.io.IOException: Failed to copy full contents from '/Users/hailong/StudioProjects/lezhu/lezhu/build/tmp/transformClassesWithDoubleClickTransformForDevelopmentDebug/2f557365_classes.jar' to '/Users/hailong/StudioProjects/lezhu/lezhu/build/intermediates/transforms/DoubleClickTransform/development/debug/0.jar'
	at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1157)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1091)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
	at github.leavesczy.asm.base.BaseTransform.forEachJar(BaseTransform.kt:113)
	at github.leavesczy.asm.base.BaseTransform.access$forEachJar(BaseTransform.kt:26)
	at github.leavesczy.asm.base.BaseTransform$transform$$inlined$forEach$lambda$1.invoke(BaseTransform.kt:46)
	at github.leavesczy.asm.base.BaseTransform$transform$$inlined$forEach$lambda$1.invoke(BaseTransform.kt:26)
	at github.leavesczy.asm.base.BaseTransform$submitTask$1.call(BaseTransform.kt:272)
	at github.leavesczy.asm.base.BaseTransform$submitTask$1.call(BaseTransform.kt:26)

**Comment by protectedMan** [comment]
查了下，在复制的过程中，源文件改变了，就会出现这个错。

**Comment by leavesCZY** [comment]
源文件改变了是什么意思呢？有没有具体的复现步骤
